name: Rust Builds

on:
  push:
    paths:
      - 'tui/**'
      - 'libsheriff/**'
      - 'server/**'
  pull_request:
    paths:
      - 'tui/**'
      - 'libsheriff/**'
      - 'server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev
      - name: libsheriff Build
        working-directory: libsheriff
        run: cargo build
      - name: libsheriff tests
        working-directory: libsheriff
        run: cargo test
      - name: TUI Build
        working-directory: tui
        run: cargo build
      - name: TUI tests
        working-directory: tui
        run: cargo test
      - name: Server Build
        working-directory: server
        run: cargo build
      - name: Server Tests
        working-directory: server
        run: cargo test
