name: TUI Rust Build

on:
  push:
    paths:
      - 'tui/**'
  pull_request:
    paths:
      - 'tui/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev
      - name: Build
        working-directory: tui
        run: cargo build --verbose
      - name: Run tests
        working-directory: tui
        run: cargo test --verbose
